version: '3.8'

services:
  switch-service:
    build: .
    container_name: switch-service
    restart: unless-stopped
    ports:
      - "3400:3400"        # 主服务端口
      - "4000-4100:4000-4100"  # 代理服务端口范围
    environment:
      - NODE_ENV=production
      - PORT_RANGE_START=4000
      - PORT_RANGE_END=4100
    volumes:
      - ./data:/app/server/data  # 持久化数据目录

  # 可选：如果你想在同一个Docker网络中运行Eureka用于测试
  eureka-server:
    image: steeltoeoss/eureka-server:latest
    container_name: eureka-server
    restart: unless-stopped
    ports:
      - "8761:8761"
    environment:
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false 